# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning Reinforcement Learning
email: ben@haanstra.nl
description: > 
  This website is about Reinforcement Learning, learning and discussion of its concepts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.com/kofzor/Learning_RL" # the base hostname & protocol for your site
github_username:  kofzor
# Build settings
markdown: kramdown
gems: ['jekyll-github-metadata']
